name: Check for New Release and Build Docker

on:
  schedule:
    - cron: '19 22 * * *'
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get latest release info
      id: get_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/tonutils/reverse-proxy/releases/latest)
        echo "Latest release info: $latest_release"
        echo "::set-output name=tag::$(echo $latest_release | jq -r .tag_name)"
        echo "::set-output name=published_at::$(echo $latest_release | jq -r .published_at)"
    
    - name: Compare with last known release
      id: compare_release
      run: |
        last_known_release=$(cat .last_known_release 2>/dev/null || echo "")
        latest_release=${{ steps.get_release.outputs.published_at }}
        if [ "$latest_release" != "$last_known_release" ]; then
          echo "New release found: $latest_release"
          echo "::set-output name=new_release::true"
          echo $latest_release > .last_known_release
        else
          echo "No new release. Last known release: $last_known_release"
          echo "::set-output name=new_release::false"
        fi
    
    - name: Build and push Docker if new release
      if: steps.compare_release.outputs.new_release == 'true'
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      if: steps.compare_release.outputs.new_release == 'true'
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      if: steps.compare_release.outputs.new_release == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      if: steps.compare_release.outputs.new_release == 'true'
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: m4l3vich/ton-reverse-proxy:${{ steps.get_release.outputs.tag }},m4l3vich/ton-reverse-proxy:latest
